name: Go CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure branch is up-to-date with main
        run: |
          git fetch origin main
          if git merge-base --is-ancestor origin/main @; then
            echo 'Tests are already up-to-date'
          else
            echo 'Your tests have not been updated, try to rebase main' && exit 1
          fi
      - name: Check for YAML and Test changes
        run: |
          CHANGES=$(git diff --minimal --name-only origin/main...@ | grep -E '(\.md|\.yaml|_test\.go)$' | wc -l)
          if [ "$CHANGES" -ne 0 ]; then
            echo "Changes detected in YAML or Test files: $CHANGES files changed."
            exit 1
          else
            echo "No changes in YAML or Test Go files."
          fi
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: ./go.sum
      - name: Dependencies
        working-directory: ./
        run: go mod tidy
      - name: Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
      - name: Tests
        working-directory: ./
        run: |
          go test -race -timeout 4m -v ./...
